name: Sync to Hugging Face
on:
  push:
    branches: [main] # Se activa cada vez que subes cambios a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        env:
          SPP_TOKEN: ${{ secrets.SPP_TOKEN }}
        run: git push --force https://fsotoj:$SPP_TOKEN@huggingface.co/spaces/fsotoj/spp main